export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
}

export enum CallStatus {
  IDLE = 'IDLE',
  CONNECTING = 'CONNECTING',
  ACTIVE = 'ACTIVE',
  ANALYZING = 'ANALYZING',
  COMPLETED = 'COMPLETED',
}

export interface Patient {
  _id: string;
  name: string;
  email: string;
  phone: string;
  lastVisit?: string;
  notes?: string;
  riskProfile: 'Low' | 'Moderate' | 'High';
}

export interface Appointment {
  _id: string;
  patientId: string;
  patientName: string; // Denormalized for easier display
  date: string; // ISO string
  durationMinutes: number;
  status: AppointmentStatus;
  type: 'Check-up' | 'Follow-up' | 'Emergency' | 'Consultation';
  notes: string;
  transcription?: string; // From Vapi call
  aiSummary?: string; // Generated by Gemini
}

export interface CallLog {
  _id: string;
  patientId: string;
  timestamp: string;
  durationSeconds: number;
  transcript: string;
  summary: string;
  sentiment: 'Positive' | 'Neutral' | 'Negative';
}

export interface DashboardStats {
  totalAppointments: number;
  pendingconfirmations: number;
  completedToday: number;
  revenue: number;
}
